export const sample_books = [
  {
    id: '1',
    title: 'The Great Gatsby', 
    publicationYear: 1925,
    price: 15,
    favorite: false,
    genres: ['Classic', 'Fiction'], 
    stars: 4.5,
    coverImageUrl: 'great-gatsby.jpg', 
    tags: ['Classic', 'American', 'Novel'],
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    publicationYear: 1960,
    price: 20,
    favorite: true,
    genres: ['Classic', 'Drama'],
    stars: 5,
    coverImageUrl: 'to-kill-a-mockingbird.jpg',
    tags: ['Classic', 'Historical', 'Legal'],
  },
  {
    id: '3',
    title: '1984',
    publicationYear: 1949,
    price: 18,
    favorite: false,
    genres: ['Dystopian', 'Science Fiction'],
    stars: 3.5,
    coverImageUrl: '1984.jpg',
    tags: ['Dystopia', 'Political Fiction'],
  },
  {
    id: '4',
    title: 'The Hobbit',
    publicationYear: 1937,
    price: 25,
    favorite: true,
    genres: ['Fantasy', 'Adventure'],
    stars: 3,
    coverImageUrl: 'the-hobbit.jpg',
    tags: ['Fantasy', 'Adventure', 'Epic'],
  },
  {
    id: '5',
    title: "Harry Potter and the Philosopher's Stone",
    publicationYear: 1997,
    price: 30,
    favorite: true,
    genres: ['Fantasy', 'Adventure'],
    stars: 3.5,
    coverImageUrl: 'harry-potter-1.jpg',
    tags: ['Magic', 'Wizard', 'Adventure'],
  },
  {
    id: '6',
    title: 'Pride and Prejudice',
    publicationYear: 1813,
    price: 22,
    favorite: false,
    genres: ['Classic', 'Romance'],
    stars: 4.0,
    coverImageUrl: 'pride-and-prejudice.jpg',
    tags: ['Classic', 'Romance', 'Historical'],
  },
];
